spring.application.name=api

# configurações fonte de dados h2 :
spring.datasource.url=jdbc:h2:mem:clyvoVetDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# configurações do controle h2 (para conseguir ver o BD no navegador) :
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# configurações do JPA hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true