spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/clyvo}
spring.datasource.username=${DB_USERNAME:clyvo}
spring.datasource.password=${DB_PASSWORD:clyvo}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
