-- CLYVO - schema PostgreSQL 16 correspondente as entidades JPA atuais.
-- Executado automaticamente pela imagem PostgreSQL apenas em volume vazio.
-- Este arquivo cria somente estrutura; os dados de demonstracao ficam separados.

BEGIN;

CREATE TABLE tutor (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(200) NOT NULL,
    email varchar(400) NOT NULL,
    cpf varchar(11) NOT NULL,
    phone_number varchar(11) NOT NULL,
    password varchar(11) NOT NULL,
    role varchar(255) NOT NULL,
    CONSTRAINT pk_tutor PRIMARY KEY (id)
);

CREATE TABLE veterinarian (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(200) NOT NULL,
    email varchar(400) NOT NULL,
    cpf varchar(11) NOT NULL,
    phone_number varchar(11) NOT NULL,
    password varchar(11) NOT NULL,
    role varchar(255) NOT NULL,
    crmv_number varchar(6),
    crmv_state varchar(2),
    cnpj varchar(14) NOT NULL,
    CONSTRAINT pk_veterinarian PRIMARY KEY (id)
);

CREATE TABLE animal (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(150) NOT NULL,
    weight real NOT NULL,
    height real NOT NULL,
    age integer NOT NULL,
    race varchar(255) NOT NULL,
    species varchar(255) NOT NULL,
    history text,
    tutor_id bigint NOT NULL,
    CONSTRAINT pk_animal PRIMARY KEY (id),
    CONSTRAINT uk_animal_tutor_name UNIQUE (tutor_id, name),
    CONSTRAINT fk_animal_tutor FOREIGN KEY (tutor_id) REFERENCES tutor (id)
);

CREATE TABLE tb_veterinarian_tutor_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    veterinarian_id bigint NOT NULL,
    tutor_id bigint NOT NULL,
    status varchar(255) NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT pk_veterinarian_tutor_links PRIMARY KEY (id),
    CONSTRAINT uk_veterinarian_tutor_link UNIQUE (veterinarian_id, tutor_id),
    CONSTRAINT ck_veterinarian_tutor_link_status
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    CONSTRAINT fk_link_veterinarian FOREIGN KEY (veterinarian_id) REFERENCES veterinarian (id),
    CONSTRAINT fk_link_tutor FOREIGN KEY (tutor_id) REFERENCES tutor (id)
);

CREATE TABLE tb_appointments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    animal_id bigint NOT NULL,
    tutor_id bigint NOT NULL,
    veterinarian_id bigint NOT NULL,
    scheduled_at timestamp(6) without time zone NOT NULL,
    reason varchar(1000) NOT NULL,
    status varchar(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT pk_appointments PRIMARY KEY (id),
    CONSTRAINT ck_appointment_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED')),
    CONSTRAINT fk_appointment_animal FOREIGN KEY (animal_id) REFERENCES animal (id),
    CONSTRAINT fk_appointment_tutor FOREIGN KEY (tutor_id) REFERENCES tutor (id),
    CONSTRAINT fk_appointment_veterinarian FOREIGN KEY (veterinarian_id) REFERENCES veterinarian (id)
);

CREATE TABLE tb_medical_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    animal_id bigint NOT NULL,
    veterinarian_id bigint NOT NULL,
    appointment_id bigint NOT NULL,
    diagnosis varchar(500) NOT NULL,
    description varchar(4000) NOT NULL,
    weight real,
    temperature real,
    observations varchar(4000),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT pk_medical_records PRIMARY KEY (id),
    CONSTRAINT uk_medical_record_appointment UNIQUE (appointment_id),
    CONSTRAINT fk_medical_record_animal FOREIGN KEY (animal_id) REFERENCES animal (id),
    CONSTRAINT fk_medical_record_veterinarian FOREIGN KEY (veterinarian_id) REFERENCES veterinarian (id),
    CONSTRAINT fk_medical_record_appointment FOREIGN KEY (appointment_id) REFERENCES tb_appointments (id)
);

CREATE TABLE tb_prescriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    medical_record_id bigint NOT NULL,
    instructions varchar(4000),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT pk_prescriptions PRIMARY KEY (id),
    CONSTRAINT uk_prescription_medical_record UNIQUE (medical_record_id),
    CONSTRAINT fk_prescription_medical_record FOREIGN KEY (medical_record_id) REFERENCES tb_medical_records (id)
);

CREATE TABLE tb_prescription_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    prescription_id bigint NOT NULL,
    medication_name varchar(200) NOT NULL,
    dosage varchar(200) NOT NULL,
    frequency varchar(200) NOT NULL,
    duration varchar(200) NOT NULL,
    route varchar(100) NOT NULL,
    instructions varchar(1000),
    item_order integer,
    CONSTRAINT pk_prescription_items PRIMARY KEY (id),
    CONSTRAINT fk_prescription_item_prescription FOREIGN KEY (prescription_id) REFERENCES tb_prescriptions (id)
);

CREATE TABLE tb_exams (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    medical_record_id bigint NOT NULL,
    exam_name varchar(200) NOT NULL,
    exam_type varchar(200),
    status varchar(255) NOT NULL,
    request_date timestamp(6) without time zone NOT NULL,
    result_date timestamp(6) without time zone,
    result varchar(4000),
    observations varchar(4000),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT pk_exams PRIMARY KEY (id),
    CONSTRAINT ck_exam_status CHECK (status IN ('REQUESTED', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT fk_exam_medical_record FOREIGN KEY (medical_record_id) REFERENCES tb_medical_records (id)
);

CREATE TABLE tb_vaccinations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    animal_id bigint NOT NULL,
    veterinarian_id bigint NOT NULL,
    vaccine_name varchar(200) NOT NULL,
    application_date date NOT NULL,
    next_dose_date date,
    batch_number varchar(100),
    manufacturer varchar(200),
    observations varchar(4000),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT pk_vaccinations PRIMARY KEY (id),
    CONSTRAINT fk_vaccination_animal FOREIGN KEY (animal_id) REFERENCES animal (id),
    CONSTRAINT fk_vaccination_veterinarian FOREIGN KEY (veterinarian_id) REFERENCES veterinarian (id)
);

CREATE TABLE tb_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    message varchar(255) NOT NULL,
    type varchar(255) NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp(6) without time zone,
    tutor_id bigint,
    veterinarian_id bigint,
    link_id bigint,
    CONSTRAINT pk_notifications PRIMARY KEY (id),
    CONSTRAINT ck_notification_type CHECK (type IN (
        'LINK_REQUEST_SENT', 'LINK_REQUEST_RECEIVED', 'LINK_REQUEST_ACCEPTED',
        'LINK_REQUEST_REJECTED', 'APPOINTMENT_REQUESTED', 'APPOINTMENT_CONFIRMED',
        'APPOINTMENT_CANCELLED', 'APPOINTMENT_COMPLETED', 'MEDICAL_RECORD_CREATED',
        'PRESCRIPTION_CREATED', 'EXAM_REQUESTED', 'EXAM_RESULT_AVAILABLE',
        'EXAM_CANCELLED', 'VACCINATION_REGISTERED'
    )),
    CONSTRAINT fk_notification_tutor FOREIGN KEY (tutor_id) REFERENCES tutor (id),
    CONSTRAINT fk_notification_veterinarian FOREIGN KEY (veterinarian_id) REFERENCES veterinarian (id),
    CONSTRAINT fk_notification_link FOREIGN KEY (link_id) REFERENCES tb_veterinarian_tutor_links (id)
);

CREATE TABLE tb_conversations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tutor_id bigint NOT NULL,
    veterinarian_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT pk_conversations PRIMARY KEY (id),
    CONSTRAINT uk_conversation_tutor_veterinarian UNIQUE (tutor_id, veterinarian_id),
    CONSTRAINT fk_conversation_tutor FOREIGN KEY (tutor_id) REFERENCES tutor (id),
    CONSTRAINT fk_conversation_veterinarian FOREIGN KEY (veterinarian_id) REFERENCES veterinarian (id)
);

CREATE TABLE tb_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    conversation_id bigint NOT NULL,
    sender_type varchar(20) NOT NULL,
    content varchar(2000) NOT NULL,
    is_read boolean NOT NULL,
    sent_at timestamp(6) without time zone NOT NULL,
    read_at timestamp(6) without time zone,
    CONSTRAINT pk_messages PRIMARY KEY (id),
    CONSTRAINT ck_message_sender_type CHECK (sender_type IN ('TUTOR', 'VETERINARIAN')),
    CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES tb_conversations (id)
);

-- PostgreSQL nao cria indices automaticamente para FKs; estes cobrem as consultas atuais.
CREATE INDEX ix_link_tutor_status ON tb_veterinarian_tutor_links (tutor_id, status);
CREATE INDEX ix_link_veterinarian_status ON tb_veterinarian_tutor_links (veterinarian_id, status);
CREATE INDEX ix_appointment_tutor_scheduled ON tb_appointments (tutor_id, scheduled_at);
CREATE INDEX ix_appointment_veterinarian_status_scheduled ON tb_appointments (veterinarian_id, status, scheduled_at);
CREATE INDEX ix_medical_record_animal_created ON tb_medical_records (animal_id, created_at DESC);
CREATE INDEX ix_prescription_item_order ON tb_prescription_items (prescription_id, item_order);
CREATE INDEX ix_exam_medical_record_request ON tb_exams (medical_record_id, request_date DESC);
CREATE INDEX ix_vaccination_animal_application ON tb_vaccinations (animal_id, application_date DESC);
CREATE INDEX ix_vaccination_animal_next_dose ON tb_vaccinations (animal_id, next_dose_date);
CREATE INDEX ix_notification_tutor_created ON tb_notifications (tutor_id, created_at DESC);
CREATE INDEX ix_notification_veterinarian_created ON tb_notifications (veterinarian_id, created_at DESC);
CREATE INDEX ix_conversation_tutor_updated ON tb_conversations (tutor_id, updated_at DESC);
CREATE INDEX ix_conversation_veterinarian_updated ON tb_conversations (veterinarian_id, updated_at DESC);
CREATE INDEX ix_message_conversation_sent ON tb_messages (conversation_id, sent_at, id);
CREATE INDEX ix_message_unread ON tb_messages (conversation_id, sender_type, id) WHERE is_read = false;

COMMENT ON TABLE tutor IS 'Responsaveis pelos animais atendidos no CLYVO.';
COMMENT ON COLUMN tutor.cpf IS 'CPF usado como identificador funcional do Tutor na API atual.';
COMMENT ON COLUMN tutor.password IS 'Senha legada; a aplicacao atual ainda nao usa hash.';

COMMENT ON TABLE veterinarian IS 'Profissionais veterinarios cadastrados no CLYVO.';
COMMENT ON COLUMN veterinarian.crmv_number IS 'Numero do registro profissional do Veterinario.';
COMMENT ON COLUMN veterinarian.crmv_state IS 'UF do registro CRMV.';

COMMENT ON TABLE animal IS 'Animais pertencentes a um Tutor.';
COMMENT ON COLUMN animal.tutor_id IS 'Tutor proprietario do Animal.';
COMMENT ON COLUMN animal.history IS 'Historico textual legado; prontuarios estruturados ficam em tb_medical_records.';

COMMENT ON TABLE tb_veterinarian_tutor_links IS 'Solicitacoes e vinculos entre Veterinario e Tutor.';
COMMENT ON COLUMN tb_veterinarian_tutor_links.status IS 'Estado PENDING, ACCEPTED ou REJECTED do vinculo.';

COMMENT ON TABLE tb_appointments IS 'Consultas agendadas entre Tutor, Animal e Veterinario.';
COMMENT ON COLUMN tb_appointments.scheduled_at IS 'Data e horario local agendados para a consulta.';
COMMENT ON COLUMN tb_appointments.status IS 'Estado do ciclo de vida da consulta.';

COMMENT ON TABLE tb_medical_records IS 'Prontuarios clinicos, no maximo um por consulta.';
COMMENT ON COLUMN tb_medical_records.appointment_id IS 'Consulta concluida que originou o prontuario.';
COMMENT ON COLUMN tb_medical_records.description IS 'Descricao clinica detalhada do atendimento.';

COMMENT ON TABLE tb_prescriptions IS 'Prescricoes, no maximo uma por prontuario.';
COMMENT ON COLUMN tb_prescriptions.medical_record_id IS 'Prontuario ao qual a prescricao pertence.';

COMMENT ON TABLE tb_prescription_items IS 'Medicamentos e orientacoes ordenados de uma prescricao.';
COMMENT ON COLUMN tb_prescription_items.item_order IS 'Posicao zero-based mantida pelo Hibernate.';

COMMENT ON TABLE tb_exams IS 'Exames solicitados a partir de um prontuario.';
COMMENT ON COLUMN tb_exams.status IS 'Estado REQUESTED, COMPLETED ou CANCELLED do exame.';
COMMENT ON COLUMN tb_exams.result IS 'Resultado textual; nao ha anexo no modelo atual.';

COMMENT ON TABLE tb_vaccinations IS 'Historico longitudinal de vacinacoes de um Animal.';
COMMENT ON COLUMN tb_vaccinations.veterinarian_id IS 'Veterinario autor do registro vacinal.';
COMMENT ON COLUMN tb_vaccinations.next_dose_date IS 'Proxima dose informada; sua situacao e derivada pela aplicacao.';

COMMENT ON TABLE tb_notifications IS 'Notificacoes destinadas a Tutores ou Veterinarios.';
COMMENT ON COLUMN tb_notifications.link_id IS 'Vinculo associado quando a notificacao trata de solicitacao.';

COMMENT ON TABLE tb_conversations IS 'Conversa unica para cada par Tutor e Veterinario.';
COMMENT ON COLUMN tb_conversations.updated_at IS 'Ultima atividade usada para ordenar as conversas.';

COMMENT ON TABLE tb_messages IS 'Mensagens persistidas de uma conversa.';
COMMENT ON COLUMN tb_messages.sender_type IS 'Papel do remetente: TUTOR ou VETERINARIAN.';
COMMENT ON COLUMN tb_messages.read_at IS 'Instante em que o destinatario marcou a mensagem como lida.';

COMMIT;
